spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: orcamentos-mass
  datasource:
    url: jdbc:mysql://localhost:3308/orcamentos_mass
    username: root
    password: ${ENV_MYSQL_PASSWORD}
  jpa:
    show-sql: true