spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: orcamentos-mass
  datasource:
    url: jdbc:mysql://localhost:3308/orcamentos_mass
    username: root
    password: ${ENV_MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      data-locations: classpath:db/sql/inserts_default.sql
server:
  error:
    include-message: never
jwt:
  secret:
    key: ${ENV_JWT_KEY}